# Generated by Django 2.0.5 on 2018-05-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('lugar_consulta', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('formula', models.TextField()),
                ('tratamiento', models.CharField(choices=[('SUBL', 'Sublingual'), ('SUBC', 'Subcutaneo')], default='SUBL', max_length=15)),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('Frasco00', models.DateField(blank=True, null=True)),
                ('Frasco0', models.DateField(blank=True, null=True)),
                ('Frasco1', models.DateField(blank=True, null=True)),
                ('Frasco2', models.DateField(blank=True, null=True)),
                ('Frasco3', models.DateField(blank=True, null=True)),
                ('Frasco4', models.DateField(blank=True, null=True)),
                ('Frasco5', models.DateField(blank=True, null=True)),
                ('Frasco6', models.DateField(blank=True, null=True)),
                ('Frasco7', models.DateField(blank=True, null=True)),
                ('Frasco8', models.DateField(blank=True, null=True)),
                ('Frasco9', models.DateField(blank=True, null=True)),
                ('Frasco10', models.DateField(blank=True, null=True)),
                ('Frasco11', models.DateField(blank=True, null=True)),
                ('Frasco12', models.DateField(blank=True, null=True)),
                ('Frasco13', models.DateField(blank=True, null=True)),
                ('Frasco14', models.DateField(blank=True, null=True)),
                ('Frasco15', models.DateField(blank=True, null=True)),
                ('Frasco16', models.DateField(blank=True, null=True)),
                ('Frasco17', models.DateField(blank=True, null=True)),
                ('Frasco18', models.DateField(blank=True, null=True)),
                ('Frasco19', models.DateField(blank=True, null=True)),
                ('Frasco20', models.DateField(blank=True, null=True)),
                ('Frasco21', models.DateField(blank=True, null=True)),
                ('Frasco22', models.DateField(blank=True, null=True)),
                ('Frasco23', models.DateField(blank=True, null=True)),
                ('Frasco24', models.DateField(blank=True, null=True)),
                ('Frasco25', models.DateField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientesDB.Medicos')),
            ],
        ),
    ]
