# Generated by Django 2.0.5 on 2018-06-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
